spring:
  datasource:
    platform: postgres
#    url: jdbc:postgresql://localhost:5432/car_rental
    url: jdbc:mysql://localhost:3306/car_rental
    username: dbuser
    password: dbpass
#    driverClassName: org.postgresql.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
